/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./src/components/AppBar.vue')['default']
    AppLoadingIndicator: typeof import('./src/@core/components/app-form-elements/AppLoadingIndicator.vue')['default']
    ErrorHeader: typeof import('./src/components/ErrorHeader.vue')['default']
    IconBtn: typeof import('./src/@core/components/IconBtn.vue')['default']
    ImageUploader: typeof import('./src/components/ImageUploader.vue')['default']
    Pagination: typeof import('./src/components/Pagination.vue')['default']
    PostForm: typeof import('./src/components/PostForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
